# Generated by Django 4.0.4 on 2022-05-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quatntity',
            new_name='quantity',
        ),
    ]
